# Generated by Django 5.2.4 on 2025-08-02 15:11

import django.db.models.deletion
import testresults.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('test_file', models.FileField(blank=True, help_text='Upload test result file (logs, reports, etc.)', null=True, upload_to=testresults.models.test_file_upload_path)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this test result', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
