# frontend/Dockerfile.frontend
FROM node:18-alpine

WORKDIR /app

# Copier uniquement les fichiers nécessaires pour npm install
COPY package.json package-lock.json ./

RUN npm install

# Copier le reste des fichiers frontend
COPY . .

RUN npm run build

CMD ["npm", "start"]
