# Generated by Django 5.2.4 on 2025-07-14 15:33

import testresults.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0002_auto_20250714_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_file',
            field=models.FileField(blank=True, help_text='Upload test result file (logs, reports, etc.)', null=True, upload_to=testresults.models.test_file_upload_path),
        ),
    ]
